# This script pushes refueling history from a CSV to Firebase Realtime Database
import pandas as pd
import firebase_admin
from firebase_admin import credentials, db

# Path to your service account key (upload this to your Colab or local env)
SERVICE_ACCOUNT_PATH = 'refueling-management-firebase-adminsdk-fbsvc-67182e13f5.json'  # <-- update if needed
FIREBASE_DB_URL = 'https://refueling-management-default-rtdb.asia-southeast1.firebasedatabase.app/'

# Only initialize if not already initialized
if not firebase_admin._apps:
    cred = credentials.Certificate(SERVICE_ACCOUNT_PATH)
    firebase_admin.initialize_app(cred, {
        'databaseURL': FIREBASE_DB_URL
    })

# Read the CSV file generated by your notebook
log_df = pd.read_csv('vehicle_arrival_log.csv')

# Push each row to Firebase under 'refueling' node
ref = db.reference('refueling')
for _, row in log_df.iterrows():
    ref.push({
        'vehicleNumber': row['Vehicle Number'],
        'timestamp': row['Timestamp']
    })
print('✅ All refueling records pushed to Firebase!')
